---
- name: Установим Grafana 
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_10.0.2_amd64.deb
    state: present

- name: Запустим Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes
