---

- hosts: elasticsearch
  user: alifanov
  become: true
  become_user: root
  roles:
    - install_elasticsearch
    - config_logstash

- hosts: kibana
  user: alifanov
  become: true
  become_user: root
  roles:
    - install_kibana
    - config_kibana

- hosts: web
  user: alifanov
  become: true
  become_user: root
  roles:
    - install_filebeat
    - config_filebeat
