---

- hosts: grafana
  user: alifanov
  become: true
  become_user: root
  roles:
    - install_grafana

- hosts: prometheus
  user: alifanov
  become: true
  become_user: root
  roles:
    - config_prometheus
