- name: Compile NGINX from sources
  hosts: web

  tasks:
  - name: "Скачиваем архив:"
    copy:
      src: /home/alifanov/source/nginx-1.9.5.tar.gz
      dest: /tmp/nginx-1.9.5.tar.gz
      remote_src: yes

  - name: "Распаковываем NGINX"
    unarchive:
      copy: no
      src: /tmp/nginx-1.9.5.tar.gz
      dest: /tmp/

  - name: "Создаем необходимую директорию Nginx"
    become: yes
    file:
      path: /etc/nginx
      state: directory
      owner: root
      mode: 0755
      
  - name: "Устанавливаем Nginx"
    become: yes
    shell: ./configure --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf && make && make install
    args:
      chdir: /tmp/nginx-1.9.5

- name: "Создаем директорию www"
    file:
      path: /var/www/{{ domain }}
      state: directory
      mode: '0775'

  - name: "Удаляем дефолтный шаблон сайта:"
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: "Копируем конфигурационный файл:"
    copy:
      src: ./nginx/nginx.conf 
      dest: /etc/nginx/
    notify: restart nginx

  - name: "Копируем конфигурационный файл сайта:"
    template:
      src: ./nginx/site.conf
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  - name: "Копируем нашу заглушку для сайта"
    template:
      src: ./nginx/index.html
      dest: /var/www/html/index.nginx-debian.html
        
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
