---
- name: Удаляем /etc/nginx/sites-enabled/default
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Изменяем /etc/nginx/nginx.conf
  template:
    src: templates/nginxconfig
    dest: /etc/nginx/nginx.conf

- name: Создаем /etc/nginx/conf.d/site.conf
  template:
    src: templates/siteconf
    dest: /etc/nginx/conf.d/site.conf

- name: Изменяем
  template:
    src: templates/content
    dest: /var/www/html/index.nginx-debian.html
