---
# tasks file for web
- name: Delete /etc/nginx/sites-enabled/default
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Change /etc/nginx/nginx.conf
  template:
    src: templates/nginxconfig
    dest: /etc/nginx/nginx.conf

- name: Create /etc/nginx/conf.d/diplom.conf
  template:
    src: templates/diplomconf
    dest: /etc/nginx/conf.d/diplom.conf

- name: Change
  template:
    src: templates/content
    dest: /var/www/html/index.nginx-debian.html
